# Use root/example as user/password credentials
version: '3.1'

services:
  # mySQL Database with init-scripts from ./db/init
  db:
    image: mysql:8
    # specifying platform to override ARM-machines trying to pull non-existing ARM version of the image
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: sensor_network
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d   # Link init scripts to the container
      - ./db/mysql:/var/lib/mysql  # Link a volume from host to persist the data

  # Open Data Portal Web Application with API, built using `./Dockerfile`
  app:
    image: ghcr.io/sensor-network/open-data-portal-app:main
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_DB_HOST: db
      NEXT_PUBLIC_DB_USER: admin
      NEXT_PUBLIC_DB_PASSWORD: admin
      NEXT_PUBLIC_DB_DATABASE: sensor_network
      NEXT_PUBLIC_API_KEY: default
